server:  servlet:    encoding:      charset: utf-8      enabled: true

spring:
  datasource:    driver-class-name:     url:     username:     password:     
  
  jpa:    hibernate:      ddl-auto: update
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    show-sql: true